### ISSUE TITLE
incorrect generate_output functionality

### ISSUE THREAD

**Issue by zakrush** [anthonyharrison/lib4sbom#2]
Hello. 
Thank you for package. 
I found some error for function SBOMOutput() generate_output
```python
from lib4sbom.parser import SBOMParser
from lib4sbom.generator import SBOMOutput


base_parse = SBOMParser()
base_parse.parse_file('test_data/almalinux.spdx')


sbom_output = SBOMOutput(output_format='Tag')
sbom_output.generate_output(base_parse.get_sbom())
```
the output is only keys of dataset:
```
type
files
packages
relationships
document
```
Is it expected behavior? 

My case it's parse sbom, delete some packages and relationships and then get new sbom on this date. 
generate() functions is not for me, becouse it changes some metadata like tools for example. 

sbom file attached.

**Comment by anthonyharrison** [comment]
@zakrush I can't see the SBOM. 

I can reproduce the error. 

However, the following code does work

```python
my_generator = SBOMGenerator(False, sbom_type="spdx", format="tag")
# Will be displayed on console
my_generator.generate("TestApp", base_parse.get_sbom())
```

SBOMOutput is intended to be called after the Generator function, so I suspect that something is unitialised which is why you are getting the result.

An SBOM is intended to be static so removing packages will require a new SBOM to be generated as the package identifiers will change.

**Comment by zakrush** [comment]
I'm so sorry. 
[almalinux.txt](https://github.com/anthonyharrison/lib4sbom/files/11742200/almalinux.txt)
There is attachment.

So, I found other incorrecting functionality. 
Ex. you can found libselinux package in my spdx. After parse it, function parse changed version field from 2.9-5.el8 to  2.9

Also, I lost some fields. I think that fields should be attachment dinamical. 

And my main case: 
I'll want use it for trivy tool. 
https://github.com/aquasecurity/trivy where I get the sbom for docker image
`trivy image --format spdx almalinux/8-base:8.5-20211112 -o test_data/node-alma.spdx`
the command are working correct:
`trivy sbom test_data/node-alma.spdx`
But if i parse and generate new sbom, it doesn't

**Comment by anthonyharrison** [comment]
@zakrush The approach to version numbers has been to validate versions as semantic versions (a.b.c). So 2.9-5.el8 becomes 2.9. I will see if I can make this validation optional so the original version is maintained.

There are some SPDX fields which aren't currently captured. PackageAttributionText being one. I selected the fields which had a good match between SPDX and CycloneDX but can add the missing fields so that they are preserved. If fields are not valid SPDX fields, they will not be preserved.

Note that regenerating the SBOM will not reproduce the same SBOM. The Identifiers for each package will be different, the order of the fields may differ and comments are not preserved.

**Comment by anthonyharrison** [comment]
@zakrush Looking at the sample file and the SPDX specification, the values for PackageAttributionText are not in line with the specification. It should be a free format text surrounded by <text>,,.</text> rather than multiple fields. It would appear that Trivy is using this attribute to define non-standard attributes.

Many of the License fields are also invalid as the license value is not a valid SPDX license identifier. This is a common problem for many SBOM generators.

Whilst these are problems with Trivy rather than Lib4SBOM, I will update LIB4SBOM to support PacckageAttributionText (in line with the SPDX specification). LIB4SBOM should already handle the invalid licenses (when generating an SBOM) and ensure that the license values are valid.

**Comment by zakrush** [comment]
Ok. Thanks. I have also other problems with parsing CyclonDX (error) but it was other issue. 
Also I wrote self althoritm fo my flow. This packet is not fo me, unfortunately but I can give some error in you lib.

**Comment by anthonyharrison** [comment]
@zakrush The SBOM extracted from a file is just the raw data; the SBOM data passed to the output engine should be the SBOM data formatted according the the type and format of the SBOM. They are not the same! The SBOMOutput class is just handling to storing of the data in a file or outputting to the console and tt doesn't do any processing of the data. If you pass the wrong type of data to the SBOMOutput class, the output is undetermined and in some cases will result in an exception being raised. 

However asSBOMOutput is only intended as an internal class to Lib4SBOM (as it should only be called after a SBOM has been generated), I will update the README to remove details of this class.
