### ISSUE TITLE
Same package name in different manifest files does not appear after parsing the SPDX / CycloneDx file

### ISSUE THREAD

**Issue by rms-sth** [anthonyharrison/lib4sbom#36]
Lets say I have two manifest files
- requirements.txt : It contains flask==2.0.3
- dev/requirements.txt : It contains flask==2.0.3 

The generated SBOM packages looks like this:

```json
[
  {
    "name": "flask",
    "SPDXID": "SPDXRef-Package-python-flask-7aeb2a6c081f1782",
    "versionInfo": "2.0.3",
    "supplier": "NOASSERTION",
    "downloadLocation": "NOASSERTION",
    "filesAnalyzed": false,
    "sourceInfo": "acquired package info from installed python package manifest file: /dev/requirements.txt",
    "licenseConcluded": "NOASSERTION",
    "licenseDeclared": "NOASSERTION",
    "copyrightText": "NOASSERTION",
    "externalRefs": [
      {
        "referenceCategory": "SECURITY",
        "referenceType": "cpe23Type",
        "referenceLocator": "cpe:2.3:a:python-flask:python-flask:2.0.3:*:*:*:*:*:*:*"
      }
    ]
  },
  {
    "name": "flask",
    "SPDXID": "SPDXRef-Package-python-flask-4947d30b71b34501",
    "versionInfo": "2.0.3",
    "supplier": "NOASSERTION",
    "downloadLocation": "NOASSERTION",
    "filesAnalyzed": false,
    "sourceInfo": "acquired package info from installed python package manifest file: /requirements.txt",
    "licenseConcluded": "NOASSERTION",
    "licenseDeclared": "NOASSERTION",
    "copyrightText": "NOASSERTION",
    "externalRefs": [
      {
        "referenceCategory": "SECURITY",
        "referenceType": "cpe23Type",
        "referenceLocator": "cpe:2.3:a:python-flask:python-flask:2.0.3:*:*:*:*:*:*:*"
      }
    ]
  }
]

```

But after parsing with lib4sbom only one of the package is returned by ```get_packages()```

Desire output: Both packages should be returned after parsing.

**Comment by mastersans** [comment]
Hey @rms-sth Is this issue also present in cyclonedx format ? also bug same as this was fixed in [ISSUE](https://github.com/anthonyharrison/lib4sbom/issues/33) so this may be fixed now can you try it out with latest commit of lib4sbom?

**Comment by anthonyharrison** [comment]
@rms-sth Thanks for the explanation.

Each project should have a separate SBOM. Each project is independent. If you want to aggregate together into a single SBOM, you need to either combine the two projects so that you can then create a new SBOM which is the superset of both projects or merge the two SBOMs together. There are a number of tools which claim to merge SBOMs together (e.g. [sbommerge](https://github.com/anthonyharrison/sbommerge))

However, the merged SBOM is really representing a system (consisting of two projects) and the correct way of representing this is through another type of BOM, the OBOM (Operations Bill of Materials) which is only supported by CycloneDX (and not yet by Lib4sbom).
