### ISSUE TITLE
get_sbom() doesn't return SBOMData 

### ISSUE THREAD

**Issue by 0x73746F66** [anthonyharrison/lib4sbom#46]
As title states, the method `get_sbom()` specifically both `CycloneDXParser.get_sbom()` and `SBOM.get_sbom()`

These have type hint they return `SBOMData` but in fact return the property `sbom` which is a `dict`.

I can't actually find how to access the `SBOMData` after the parser finishes, mainly because this dict only includes `{'type': 'cyclonedx'}` and all the other data is simply missing..

reproduce data created via `cyclonedx-py requirements -o sbom.cdx.json --of json --sv 1.6 requirements.txt` with any libs really.

**Comment by anthonyharrison** [comment]
Can you provide an example of the SBOM which you are trying to parse?

If the parser fails, then no data will be returned in the SBOMData structure. This is often due to a failure in the processing of the metadata. There have been some recent changes in the parsing of the metadata (to make it more robust) so using the latest version in the repo may work.

**Comment by 0x73746F66** [comment]
I did describe how to get the SBOM data, so instead I might try trunk and see if the problem persists

**Comment by anthonyharrison** [comment]
> I did describe how to get the SBOM data, so instead I might try trunk and see if the problem persists

It seems to work with the latest version in the repo.
